### ISSUE TITLE
release melodic

### ISSUE THREAD

**Issue by k-okada** [anqixu/ueye_cam-release#1]
@anqixu Would you mind releasing ueye_cam to melodic? Thanks in advance.

**Comment by anqixu** [comment]
Sorry it's took me this long to respond. After rosdisto PR merges, then prerelease, and release should follow soon.

https://github.com/ros/rosdistro/pull/26102

**Comment by anqixu** [comment]
https://github.com/anqixu/rosdistro/pull/new/bloom-ueye_cam-36
